### PR TITLE
Added sk_region_flags which returns flags as associative array

### PR DESCRIPTION
**Pull request by Ecconia**
sk_region_info returns the flags as array with arrays, which is not very practical to use, since one need to format it, to check if keys are existent, or to easily grab a key value.

### CODE REVIEW

**Comment by Ecconia** [comment]
I decided to create a new function for this, since I didn't want to mess up the sk_region_info code for returning the flags, (keep the interface the same). Also I prefer having this as a procedure.
I didn't add the version method, since I didn't know how to deal with changes like this.
Its my first experience with a CH extension, it compiles it can be used :P There shouldn't be mistakes :)

**Comment by jb-aero** [comment]
Could you provide an example of how sk_region_info returns flags (and how sk_region_flags will)? I'm not going to be able to get on Minecraft in a reasonable timeframe.

**Comment by Ecconia** [comment]
I can do that sure, the example here or as methods in the two named functions, example()?
Whatever you prefer. Won't have time before Monday probably.

**Comment by Ecconia** [comment]
Usage and return examples:

New: `@flags = sk_region_flags(@region, @world)`
@flags contains: `{farewell: Read rules and stuff, greeting: Welcome to spawn, use: ALLOW}`

Old: `@flags = sk_region_info(@region, @world, 3)`
@flags contains: `{{use, ALLOW}, {greeting, Welcome to spawn}, {farewell, Read rules and stuff}}`

As you can see the new procedure has the associative array with key:value. That allows:
```
@bool = array_index_exists(@flags, 'does_this_flag_exist?') //Check if flag is set.
@flag = @flags['greeting'] //Access to the values for the flags.
@flagkeys = array_keys(@flags) //Returning all existing flags as array.
```

Personally I see the usage of these already existing procedures to work with @flags much more comfortable than looping over an array, to check if flags are set, to get values or all existing flags.

My personal usage is simple to check if a certain flag is set, if so I want to access the usage:
```
//Tp'ing a player to a position in a plot if a spawn flag is set:
if(!array_index_exists(@flags, 'spawn') {
    die('This plot has no spawn defined); //Example cancel
}
set_ploc(@player, @flags['spawn']); //Simplified
```

**Comment by jb-aero** [comment]
Ah, yeah that's how I imagined what you were describing. Not sure why it was done that way, or who did it as it was done when WG stuff was part of CH. But I thank you for your contribution, and I'm sure others will as well!

**Pull request merged**
