### PR TITLE
Bugfixes & extra support in sk_posX().

### PR DESCRIPTION
**Pull request by Pieter12345**
- sk_posX() now accepts "null" as location array argument, which clears position X (with WE CUI support). Previously, supplying "null" would select point (0, 0, 0).
- Bugfix: sk_posX() now returns the real selection, rather than a cached out-of-sync selection from WorldEdit. This fixes sk_posX() returning non-null after using the "//desel" command in-game.
- sk_posX() no longer uses (0, 0, 0) detection to return null (due to the point mentioned above, this can now be detected directly).
- Bugfix: Using sk_posX() as setter on the first join after a server restart can potentially create a new LocalSession with no references to it, resulting in not setting the position. This has been fixed. Note that this might never happen when a user has WorldEdit CUI installed (which executes "/we cui" on join).
- Updated docs. sk_posX(null) defaults to using "null" as a player, since this player actually exists. Recommended usage is sk_posX(player, locationArray) to prevent confusion.
- Replaced decrecated ObjectGenerator.vector(vec, target) calls.
- Updated outdated sk89q maven repository.

### CODE REVIEW

**Comment by jb-aero** [comment]
Somebody probably said it in IRC, but since I can't check that atm, Y U USE ECLIPSE. And does that change not affect compatibility with other things?

**Comment by Pieter12345** [comment]
From maven documentation:
> pluginManagement: is an element that is seen along side plugins. Plugin Management contains plugin elements in much the same way, except that rather than configuring plugin information for this particular project build, it is intended to configure project builds that inherit from this one. However, this only configures plugins that are actually referenced within the plugins element in the children. The children have every right to override pluginManagement definitions.
I would recommend testing this with your setup, but it should not make any difference as far as I understand.

For some reason, Eclipse gives an error without these (even though a maven install works properly).
Errors:
`Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:templating-maven-plugin:1.0-alpha-3:filter-sources (execution: filter-src, phase: generate-sources)`
`Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:exec-maven-plugin:1.2.1:java (execution: cache-annotations, phase: process-classes)`

I'm used to Eclipse, especially since javadocs are shown on hover, which NetBeans doesn't appear to do. Also, Eclipse shows auto-fixes for errors and warnings on hover, where NetBeans requires you to press left alt + enter (which are far apart) to show the same auto-fixes.  And last, when ctrl+hovering s method, Eclipse shows an option to open the declaration or implementation(s), where NetBeans just opens the declaration. I've tried NetBeans since CH didn't pass any tests on Eclipse (since I have a whitespace in my workspace dir.. made a PR for that CH bug recently), but I've had too many of these frequently used functionalities that required more effort to work with, resulting in a lot of pain to use NetBeans. If you have a solution, I'm open for trying other IDE's. This answer might be a bit longer than expected, but now you know :)

**Comment by jb-aero** [comment]
Ah okay, when I get a chance I will double check locally. I use IntelliJ Community Edition, it has the same or similar features to what you've listed, but (usually) feels really smart. In fairness I haven't touched Eclipse in over five years.

**Comment by Pieter12345** [comment]
I found out that it is possible to simply ignore the errors in Eclipse and still build it successfully (likely since Eclipse just calls maven to do the job). This makes the extra tags unnecessary, so I'd recommend pulling all changes except for the pom pluginManagement tag.

**Comment by Pieter12345** [comment]
Due to some bug in my git setup, I'm unable to perform rebases. Feel free to put both pluginManagement commits and the fixup commit together or just pull it as it is.

**Comment by jb-aero** [comment]
Ah good timing, I was going to check if there was a way to ignore that particular commit.

**Pull request merged**
